#pragma once
#include <stdint.h>
#include <string.h>

// Validated resting poses — angles in radians (hip, knee per leg)
// Generated by firmware/test/pose_generator, verified via forward kinematics

struct DogPose {
    const char* name;
    const char* description;
    float angles[8];  // FL_hip, FL_knee, FR_hip, FR_knee, RL_hip, RL_knee, RR_hip, RR_knee
};

static const DogPose POSES[] = {
    {"stand",    "Default standing pose",
     {0.3000f, -0.6000f, 0.3000f, -0.6000f, 0.3000f, -0.6000f, 0.3000f, -0.6000f}},

    {"tall",     "Tall upright stance",
     {0.1500f, -0.5406f, 0.1500f, -0.5406f, 0.1500f, -0.5406f, 0.1500f, -0.5406f}},

    {"crouch",   "Low crouched stance",
     {0.5000f, -0.8000f, 0.5000f, -0.8000f, 0.5000f, -0.8000f, 0.5000f, -0.8000f}},

    {"rest",     "Relaxed rest, slightly lower",
     {0.4000f, -0.5629f, 0.4000f, -0.5629f, 0.4000f, -0.5629f, 0.4000f, -0.5629f}},

    {"alert",    "Alert stance, forward lean",
     {0.2000f, -0.5691f, 0.2000f, -0.5691f, 0.4000f, -0.5629f, 0.4000f, -0.5629f}},

    {"sit",      "Sitting - front straight, rear tucked",
     {0.0500f, -0.4639f, 0.0500f, -0.4639f, 1.0000f, -1.4000f, 1.0000f, -1.4000f}},

    {"lie_down", "Lying flat, all legs folded",
     {0.8000f, -1.2000f, 0.8000f, -1.2000f, 0.8000f, -1.2000f, 0.8000f, -1.2000f}},

    {"play_bow", "Play bow - front low, rear high",
     {0.7000f, -1.0000f, 0.7000f, -1.0000f, 0.1500f, -0.5406f, 0.1500f, -0.5406f}},
};

static const int NUM_POSES = sizeof(POSES) / sizeof(POSES[0]);
static const int DEFAULT_REST_POSE = 3;  // "rest" — index into POSES array

static const DogPose* find_pose(const char* name) {
    for (int i = 0; i < NUM_POSES; i++) {
        if (strcmp(name, POSES[i].name) == 0) return &POSES[i];
    }
    return nullptr;
}
